name: Workflow 2nd for Codecov example-typescript

on:
  push:
    branches:
      - '**'
    paths:
      - 'app/second/**'
      - 'app/calculator.ts'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test:second
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel: true
          carryforward: first,second
          flag-name: second
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel-finished: true
          carryforward: first,second
          flag-name: second
        env:
          COVERALLS_SERVICE_NUMBER: ${{ github.sha }}
