name: Workflow 2nd for Codecov example-typescript
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test:second
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: second
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
